config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :promotions
  post '/discount_cart', to: 'cart#discount_cart', :headers => ":any"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :promotions
  belongs_to :shop
end

app/models/products_promotion.rb
class ProductsPromotion < ActiveRecord::Base

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  attr_accessor :product, :all_product

  has_and_belongs_to_many :products
  belongs_to :shop
  has_many :promotion_details, dependent: :destroy
  accepts_nested_attributes_for :promotion_details

  default_scope { order("created_at ASC") }
  enum promotion_type: %w(volume_amount spend_amount)
  enum status: %w(running stopped)

  validate :validate_product, :validate_promotion_details

  def validate_product
    if products
      products.each do |product|
        Promotion.send(promotion_type).where.not(id: self.id).each do |promotion|
          if promotion.products.pluck(:product_shopify_id).include?(product.product_shopify_id)
            errors.add(:errors, "The products #{product.name} is in another promotion")
          end
        end
      end
    end
  end

  def validate_promotion_details
    unless self.promotion_details.present?
      errors.add(:errors, "Please select the promotion details!!")
    end
  end

  after_create do
    shop = ShopifyAPI::Shop.current
    current_shop = Shop.where(shopify_domain: shop.attributes["domain"]).first || Shop.where(shopify_domain: shop.attributes["myshopify_domain"]).first
    if shop.attributes["myshopify_domain"] == "gadshack.myshopify.com"
      AddPromotionsService.add_promotion_for_gadsack(current_shop)
    elsif shop.attributes["myshopify_domain"] == "thoaivk.myshopify.com"
      AddPromotionsService.add_promotion_for_thoaivk(current_shop)
    else
      AddPromotionsService.add_promotion(current_shop)
    end
  end

  after_update do
    shop = ShopifyAPI::Shop.current
    current_shop = Shop.where(shopify_domain: shop.attributes["domain"]).first || Shop.where(shopify_domain: shop.attributes["myshopify_domain"]).first
    if shop.attributes["myshopify_domain"] == "gadshack.myshopify.com"
      AddPromotionsService.add_promotion_for_gadsack(current_shop)
    elsif shop.attributes["myshopify_domain"] == "thoaivk.myshopify.com"
      AddPromotionsService.add_promotion_for_thoaivk(current_shop)
    else
      AddPromotionsService.add_promotion(current_shop)
    end
  end

  after_destroy do
    shop = ShopifyAPI::Shop.current
    current_shop = Shop.where(shopify_domain: shop.attributes["domain"]).first || Shop.where(shopify_domain: shop.attributes["myshopify_domain"]).first
    if shop.attributes["myshopify_domain"] == "gadshack.myshopify.com"
      AddPromotionsService.add_promotion_for_gadsack(current_shop)
    elsif shop.attributes["myshopify_domain"] == "thoaivk.myshopify.com"
      AddPromotionsService.add_promotion_for_thoaivk(current_shop)
    else
      AddPromotionsService.add_promotion(current_shop)
    end
  end
end

app/models/promotion_detail.rb
class PromotionDetail < ActiveRecord::Base

  belongs_to :promotion, dependent: :destroy

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage

  has_many :promotions
  has_many :shop_backups
  has_many :products

  after_commit do
    session = ShopifyAPI::Session.new(self.shopify_domain, self.shopify_token)
    ShopifyAPI::Base.activate_session(session)
    domain = ShopifyAPI::Shop.current.attributes["domain"]
    self.domain_url = domain
  end
end

app/models/shop_backup.rb
class ShopBackup < ActiveRecord::Base
  belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :add_allow_credentials_headers

  def add_allow_credentials_headers
    response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
  end
end

app/controllers/cart_controller.rb
require "uri"
require "net/http"

class CartController < ApplicationController

  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  def discount_cart
    shop_domain =request.env["HTTP_ORIGIN"].to_s.gsub("https://", "")
    shop = Shop.where(shopify_domain: shop_domain).first || Shop.where(domain_url: shop_domain).first
    session = ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
    ShopifyAPI::Base.activate_session(session)
    original_cost = params["original_price"].gsub(".","").to_f/100
    discount_cost = params["discount_price"].gsub(".",",").gsub("$", "").gsub(",", "").to_f/100
    product_array = params["product_array"].map{|id| id.to_i }.reject{|num| num.zero?}
    title = "MISKRE_" + [*('a'..'z'),*('0'..'9')].shuffle[0,10].join
    discount_result =  false
    if discount_cost > 0 && original_cost > discount_cost
      @new_price_rule = ShopifyAPI::PriceRule.new(
          title: title,
          target_type: "line_item",
          target_selection: "entitled",
          allocation_method: "across",
          value_type: "fixed_amount",
          value: (0 - (original_cost - discount_cost)).to_s,
          usage_limit: 1,
          customer_selection: "all",
          once_per_customer: true,
          prerequisite_subtotal_range: {
              greater_than_or_equal_to: original_cost
          },
          "entitled_product_ids": product_array,
          starts_at: Time.zone.now - 14.days,
          ends_at: Time.zone.now + 2.days
      )
      @new_price_rule.save
      @new_discount_code = ShopifyAPI::DiscountCode.new(
          'price_rule_id': @new_price_rule.id,
          'code': title,
          'usage_count': 1,
          'value_type': 'fixed_amount',
          'value': (0 - (original_cost - discount_cost)).to_s
      )

      @new_discount_code.save ? (discount_result = title) : false

    end
    render json: { result: "OK", discount_code: discount_result}, status: 200
  end


  private

  def cart_param
    params.permit(:original_price, :discount_price, :items_detail, :product_array, :qty)
  end
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController

  def index
    shop = ShopifyAPI::Shop.current
    current_shop = Shop.where(shopify_domain: shop.attributes["domain"]).first || Shop.where(shopify_domain: shop.attributes["myshopify_domain"]).first
    @promotion = current_shop.promotions
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ShopifyApp::AuthenticatedController

  def index

  end

  def new
    @promotion = Promotion.new
    pages = (ShopifyAPI::Product.count.to_f / 50.to_f).ceil
    @products = []     # Collect all products in array
    (1..pages).each do |page|
      @products += ShopifyAPI::Product.all(params: { page: page, limit: 50 })
    end
  end

  def create
    shop = ShopifyAPI::Shop.current
    pages = (ShopifyAPI::Product.count.to_f / 50.to_f).ceil
    @products = []     # Collect all products in array
    (1..pages).each do |page|
      @products += ShopifyAPI::Product.all(params: { page: page, limit: 50 })
    end
    new_promotion = BuildPromotionService.build_promotion(params, shop)
    if new_promotion.blank?
      flash[:success] = "Create promotion successfully!"
      redirect_to root_path
    else
      flash[:notice] = new_promotion[:errors].join("\n")
      redirect_to root_path
    end
  end

  def update
    shop = ShopifyAPI::Shop.current
    promotion_update = BuildPromotionService.update_promotion(params, shop, params[:id])

    if promotion_update.blank?
      flash[:success] = "Create promotion successfully!"
      redirect_to root_path
    else
      flash[:notice] = promotion_update[:errors].join("\n")
      redirect_to root_path
    end
  end

  def destroy
    promotion = Promotion.find params[:id]
    if promotion.destroy
      flash[:success] = "Delete promotion successfully!"
      redirect_to root_path
    end
  end

  def edit
    pages = (ShopifyAPI::Product.count.to_f / 50.to_f).ceil
    @products = []     # Collect all products in array
    (1..pages).each do |page|
      @products += ShopifyAPI::Product.all(params: { page: page, limit: 50 })
    end
    @promotion = Promotion.find params[:id]
    @promotion.product = @promotion.products.collect{|p| p.product_shopify_id.to_i}
    @promotion.all_product = (@promotion.products.size == ShopifyAPI::Product.all.count) ? "1" : "0"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
- content_for :javascript do
  :javascript
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
#module-home-page
  %div.left-column
    %h2 Promotion
    %a.btn.btn-primary{href: new_promotion_path} Create Promotion
  %div.right-column
    .panel.panel-default
      .panel-body
        %table.table.table-striped.promotion-table
          %thead
            %tr
              %th Name
              %th Status
              %th Action
          %tbody
            - @promotion.each do |promotion|
              %tr
                %td
                  = promotion.promotion_name
                %td
                  = promotion.status.to_s
                %td
                  = link_to 'Edit', edit_promotion_path(promotion)
                  = link_to 'Destroy', promotion_path(promotion), data: {:confirm => 'Are you sure?'}, :method => :delete
%hr/
/ <h2>Webhooks</h2>
/ <haml_silent> if @webhooks.present? </haml_silent><haml_block>
/ <ul>
/ <haml_silent> @webhooks.each do |webhook| </haml_silent><haml_block>
/ <li><haml_loud> webhook.topic </haml_loud> : <haml_loud> webhook.address </haml_loud></li>
/ </haml_block>
/ </ul>
/ </haml_block><haml_silent> else </haml_silent><haml_block>
/ <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
/ </haml_block>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'turbolinks:load' : 'DOMContentLoaded';

  document.addEventListener(eventName, function flash() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
                             
    document.removeEventListener(eventName, flash)
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/promotions/_form.html.haml
= form_for @promotion do |f|
  .promotion-type
    .tab-label
      %h3 1.Promotion Type
    .tab-content
      = f.select(:promotion_type, options_for_select(PROMOTION_TYPE, selected: @promotion.promotion_type), prompt: 'Select promotion type')
  .clearfix
  %hr
  .hidden-content
    .promotion-details
      .tab-label
        %h3 2.Promotion Details
      .tab-content
        - if (@promotion.persisted? && @promotion.volume_amount?) || @promotion.new_record?
          .tier-tab.volume-option{class: "#{(@promotion.promotion_type == "volume_amount" ? "" : "hidden")}", disable: "#{(@promotion.promotion_type == "spend_amount" ? true : false)}"}
            .table-discount
              %table.table-hover.promotion-volume-table
                %thead
                  %tr
                    %th Min Qty
                    %th Discount %
                    %th
                %tbody
                  = f.fields_for :promotion_details do |detail|
                    = render "volume_option_line", detail: detail
            .button-bar
              %a.btn.btn-default{id: "add_more_volume"}  Add another tier
        - if (@promotion.persisted? && @promotion.spend_amount?) || @promotion.new_record?
          .tier-tab.spend-amount-option{class: "#{(@promotion.promotion_type == "spend_amount" ? "" : "hidden")}", disabled: "disabled"}
            %table.table-hover.promotion-spend-table
              %thead
                %tr
                  %th Min Spend
                  %th Discount
                  %th
                  %th
              %tbody
                %tr
                  %td
                    = text_field_tag nil, 'Minimum Amount Spend', class: "text_input", readonly: true
                  %td
                    = text_field_tag nil, '% Discount', class: "text_input", readonly: true
                = f.fields_for :promotion_details do |detail|
                  = render "spend_amount_option_line", detail: detail
            .button-bar
              %a.btn.btn-default{id: "add_more_spend_amount"}  Add another tier
          %hr
        .product-tab
          %h5 Select products that will have these volume discounts applied
          -#= f.association :products, as: :select, multiple: true, input_html: { class: 'chosen-select' }
          -#- if @promotion.persisted?
          -#= f.association :products, as: :select, input_html: { class: 'chosen-select', multiple: true }
          -#- else
          = f.select(:product, options_for_select(products.collect{|a| [a.attributes["title"], a.attributes["id"].to_i] }, selected: @promotion.product), { prompt: 'Select products'}, {class: "select_product" , multiple: "true" })
          -#= f.select(:products, options_for_select(ShopifyAPI::Product.all.collect{|a| [a.attributes["title"], [a.attributes["id"], a.attributes["title"]]] }), { prompt: 'Select products'}, {class: "select_product" , multiple: "true" })
          -#%h5 Select collections that will have these volume discounts applied
          -#= f.select("colection", options_for_select(ShopifyAPI::Product.all.collect{|a| [a.attributes["title"], a.attributes["id"]] }), prompt: 'Select collections')
          = f.check_box :all_product, { id: "all_products"}
          %label{:for => "all_products"} or apply these volume discounts across the entire
          .btn.btn-default#remove_products  Remove all products
          -#%hr
        -#.qty-option-tab
        -#  %h5 Sum up Quantities:
        -#  = f.radio_button("qty_option", "per_qty")
        -#  = label 'promotion[per_qty]', 'Per Quantity'``
        -#  = f.radio_button("qty_option", "per_product")
        -#  = label 'promotion[per_product]', 'Per Product'
        -#  = f.radio_button("qty_option", "per_item")
        -#  = label 'promotion[per_item]', 'Across all Selected Items'
        -#  %hr
        -#.message-tab
        -#  %h5 Upsell Message
        -#  = text_field('messages[up_sell]', nil, class: "text_input")
        -#  %h5 Success Message
        -#  = text_field('messages[success]', nil, class: "text_input")
        -#  %h5 Internal name (only you will see this)
        -#  = text_field('messages[internal]', nil, class: "text_input")
    .clearfix
    %hr
    .promotion-optional
      .tab-label
        %h3 3.Promotion Optional
      .tab-content
        .date-card-section
          .start-at
            %h5 Promotion start at
            = f.text_field(:valid_date, class: "text_input")
          .end-at
            %h5 Promotion end at
            = f.text_field(:end_date, class: "text_input")
        %hr
        -#.customer-section
        -#  %h5 Only show offer for customers tagged with any of the following
        -#  = text_field('promotion[customers]', nil, class: "text_input")
    .clearfix
    %hr
  .button-group
    = f.submit 'Save Promotion', class: 'btn btn-primary'

app/views/promotions/_spend_amount_option_line.html.haml
%tr{class: "promotion_line"}
  %td
    = detail.text_field(:qty, class: 'text_input')
  %td
    = detail.text_field(:value, class: 'text_input')
  %td
    %a.btn.btn-default{class: "remove_tier"}  Remove

app/views/promotions/_volume_option_line.html.haml
%tr{class: "promotion_line"}
  %td
    = detail.text_field(:qty, class: 'text_input')
  %td
    = detail.text_field(:value, class: 'text_input')
  %td
    %a.btn.btn-default{class: "remove_tier"}  Remove

app/views/promotions/edit.html.haml
#module-new-promotion
  .panel.panel-default
    .panel-body
      = render 'form', promotion: @promotion, products:  @products

:javascript
  $( document ).ready(function() {
     $('#promotion_valid_date').datepicker({
      format: "dd/mm/yyyy",
      startDate: '+1d'
    });

    $('#promotion_end_date').datepicker({
      format: "dd/mm/yyyy",
      startDate: '+1d'
    });

    $('#promotion_product').chosen({
      no_results_text: 'No results matched',
      width: '100%',
      disable_search: false
    });

    $("#promotion_colection").chosen()
    $("#promotion_promotion_type").chosen({
      width: '200px'
    })
  });

  $("#promotion_promotion_type").on('change', function() {
    if (this.value == "volume_amount"){
      $(".volume-option").removeClass("hidden")
      $(".spend-amount-option").addClass("hidden")
    }
    else {
      $(".volume-option").addClass("hidden")
      $(".spend-amount-option").removeClass("hidden")
    }
  });

  $("#add_more_volume").on("click", function() {
    currentdate = new Date();
    new_line = '<tr class="promotion_line"> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() +'_qty"> \
                </td> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">\
                </td> \
                <td>\
                <a class="btn btn-default remove_tier">Remove</a>\
                </td>\
                </tr>';
    submit_field = '<input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][qty]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_qty">\
                    <input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][value]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">'
    $(".promotion-volume-table").append(new_line);
    $(".promotion-volume-table").append(submit_field);
    $(".new_input_text").each(function() {
      $(this).on("change", function(){
        id = "#" + $(this).attr("name");
        value = $(this).val();
        $(id).attr("value", value);
      });
    });

    $(".volume-option").find(".remove_tier").each(function() {
      $(this).on("click", function(){
        $(this).closest(".promotion_line").next("input[type='hidden']").remove();
        $(this).closest(".promotion_line").remove();
      });
    });
  });

  $("#add_more_spend_amount").on("click", function() {
    currentdate = new Date();
    new_line = '<tr class="promotion_line"> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() +'_qty"> \
                </td> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">\
                </td> \
                <td>\
                <a class="btn btn-default remove_tier">Remove</a>\
                </td>\
                </tr>';
    submit_field = '<input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][qty]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_qty">\
                    <input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][value]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">'
    $(".promotion-spend-table").append(new_line);
    $(".promotion-spend-table").append(submit_field);
    $(".new_input_text").each(function() {
      $(this).on("change", function(){
        id = "#" + $(this).attr("name");
        value = $(this).val();
        $(id).attr("value", value);
      });
    });

    $(".spend-amount-option").find(".remove_tier").each(function() {
      $(this).on("click", function(){
        $(this).closest(".promotion_line").next("input[type='hidden']").remove();
        $(this).closest(".promotion_line").remove();
      });
    });
  });

  $(".volume-option").find(".remove_tier").each(function() {
    $(this).on("click", function(){
      $(this).closest(".promotion_line").next("input[type='hidden']").remove();
      $(this).closest(".promotion_line").remove();
    });
  });

  $(".spend-amount-option").find(".remove_tier").each(function() {
    $(this).on("click", function(){
      $(this).closest(".promotion_line").next("input[type='hidden']").remove();
      $(this).closest(".promotion_line").remove();
    });
  });

  $("#remove_products").on("click", function() {
    $('#promotion_product option:selected').removeAttr('selected');
    $('#promotion_product').trigger('chosen:updated');
  });

app/views/promotions/new.html.haml
#module-new-promotion
  .panel.panel-default
    .panel-body
      = render 'form', promotion: @promotion, products: @products
:javascript
  $( document ).ready(function() {
     $('#promotion_valid_date').datepicker({
      format: "dd/mm/yyyy",
      startDate: '+1d'
    });

    $('#promotion_end_date').datepicker({
      format: "dd/mm/yyyy",
      startDate: '+1d'
    });

    $('#promotion_product').chosen({
      no_results_text: 'No results matched',
      width: '100%',
      disable_search: false
    });

    $("#promotion_colection").chosen()
    $("#promotion_promotion_type").chosen({
      width: '200px'
    })
  });

  $("#promotion_promotion_type").on('change', function() {
    if (this.value == "volume_amount"){
      $(".volume-option").removeClass("hidden")
      $(".spend-amount-option").addClass("hidden")
    }
    else {
      $(".volume-option").addClass("hidden")
      $(".spend-amount-option").removeClass("hidden")
    }
  });

  $("#add_more_volume").on("click", function() {
    currentdate = new Date();
    new_line = '<tr class="promotion_line"> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() +'_qty"> \
                </td> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">\
                </td> \
                <td>\
                <a class="btn btn-default remove_tier">Remove</a>\
                </td>\
                </tr>';
    submit_field = '<input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][qty]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_qty">\
                    <input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][value]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">'
    $(".promotion-volume-table").append(new_line);
    $(".promotion-volume-table").append(submit_field);
    $(".new_input_text").each(function() {
      $(this).on("change", function(){
        id = "#" + $(this).attr("name");
        value = $(this).val();
        $(id).attr("value", value);
      });
    });

    $(".volume-option").find(".remove_tier").each(function() {
      $(this).on("click", function(){
        $(this).closest(".promotion_line").next("input[type='hidden']").remove();
        $(this).closest(".promotion_line").remove();
      });
    });
  });

  $("#add_more_spend_amount").on("click", function() {
    currentdate = new Date();
    new_line = '<tr class="promotion_line"> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() +'_qty"> \
                </td> \
                <td> \
                <input class="text_input new_input_text" type="number" name="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">\
                </td> \
                <td>\
                <a class="btn btn-default remove_tier">Remove</a>\
                </td>\
                </tr>';
    submit_field = '<input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][qty]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_qty">\
                    <input class="text_input" type="hidden" name="promotion[promotion_details_attributes][' + currentdate.getTime() +'][value]" id="promotion_promotion_details_attributes_' + currentdate.getTime() + '_value">'
    $(".promotion-spend-table").append(new_line);
    $(".promotion-spend-table").append(submit_field);
    $(".new_input_text").each(function() {
      $(this).on("change", function(){
        id = "#" + $(this).attr("name");
        value = $(this).val();
        $(id).attr("value", value);
      });
    });

    $(".spend-amount-option").find(".remove_tier").each(function() {
      $(this).on("click", function(){
        $(this).closest(".promotion_line").next("input[type='hidden']").remove();
        $(this).closest(".promotion_line").remove();
      });
    });
  });

  $(".spend-amount-option .volume-option").find(".remove_tier").each(function() {
    $(this).on("click", function(){
      $(this).closest(".promotion_line").next("input[type='hidden']").remove();
      $(this).closest(".promotion_line").remove();
    });
  });

  $("#remove_products").on("click", function() {
    $('#promotion_product option:selected').removeAttr('selected');
    $('#promotion_product').trigger('chosen:updated');
  });